#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=_select-job
source "$SCRIPT_DIR/_select-job" "Enter the number of the job to connect to"

srun --pty --overlap --jobid "$job_id" bash
